name: first-exercise-workflow
on: [push, pull_request]

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: 1. check Python Version
        run: python --version
      - name: 2. check pip version
        run: pip --version